import { createSlice, PayloadAction } from '@reduxjs/toolkit';

export type LanguageCode = 'en' | 'nl';

export type Translations = Record<string, string | string[]>;

interface LanguageState {
  currentLanguage: LanguageCode;
  translations: {
    en: Translations;
    nl: Translations;
  };
}

const initialState: LanguageState = {
  currentLanguage: 'en',
  translations: {
    en: {
      welcome: 'Welcome',
      settings: 'Settings',
      leads: 'Leads',
      booking: 'Booking',
      emailPrompting: 'Email Prompting',
      emailResponses: 'Email Responses',
      welcomeTitle: 'Welcome to QuasarLeads',
      welcomeDescription: 'Your AI-powered dashboard for lead generation and email automation',
      startCollectingLeads: 'Start Collecting Leads',
      overview: 'Overview',
      kpiDashboard: 'KPI Dashboard',
      totalLeads: 'Total Leads',
      readyForCollection: 'Ready for collection',
      emailsSent: 'Emails Sent',
      acrossAllCampaigns: 'Across all campaigns',
      responseRate: 'Response Rate',
      fromSentEmails: 'From sent emails',
      appointments: 'Appointments',
      confirmedMeetings: 'Confirmed meetings',
      quickActions: 'Quick Actions',
      gettingStarted: 'Getting Started Guide',
      configureLeadCollection: 'Configure Lead Collection',
      configureLeadCollectionDesc: 'Set up your target services and locations to collect relevant leads.',
      setupEmailSequences: 'Setup Email Sequences',
      setupEmailSequencesDesc: 'Create custom email templates and automate follow-up sequences.',
      createAppointmentTemplates: 'Create Appointment Templates',
      createAppointmentTemplatesDesc: 'Set up booking templates and confirmation emails for appointments.',
      analyzeResults: 'Analyze Results',
      analyzeResultsDesc: 'Track your performance metrics and optimize your campaigns.',
      collectNewLeads: 'Collect New Leads',
      configureEmailSequences: 'Configure Email Sequences',
      setupAppointmentTemplates: 'Setup Appointment Templates',
      viewCRMSystem: 'View CRM System',
      recentActivities: 'Recent Activities',
      noRecentActivities: 'No recent activities',
      recentLeads: 'Recent Leads',
      viewAll: 'View All',
      noLeadsFound: 'No leads found',
      lead: 'Lead',
      source: 'Source',
      openRate: 'Open Rate',
      comparedToPreviousPeriod: 'Compared to previous period',
      replyRate: 'Reply Rate',
      callsScheduled: 'Calls Scheduled',
      thisMonth: 'This month',
      conversionToCustomer: 'Conversion to Customer',
      target: 'Target',
      fromScheduledCalls: 'From scheduled calls',
      googleAdsSuccessRate: 'Google Ads Success Rate',
      highValueLeadsDetected: 'High-value leads detected',
      leadsPerMonth: 'Leads per Month',
      emailCampaignPipelineStatus: 'Email Campaign Pipeline Status',
      scheduledAppointments: 'Scheduled Appointments',
      appointment: 'Appointment',
      actions: 'Actions',
      note: 'Note',
      noAppointmentsScheduled: 'No appointments scheduled yet',
      refresh: 'Refresh',
      activeCampaign: 'Active campaign',
      scheduled: 'Scheduled',
      closedWon: 'Closed won',
      newLeads: 'New leads',
      closed: 'Closed',
      leadsCollection: 'Leads Collection',
      leadsCollectionTitle: "Leads Collection",
      leadsCollectionDescription: "Collect and manage your leads efficiently.",
      leadsDescription: 'Configure and start collecting leads from LinkedIn and Google',
      enterServices: 'Enter Services (comma-separated)',
      servicesPlaceholder: 'Web Design, Development, SEO, Marketing',
      servicesList: 'List the services you provide to find relevant leads',
      servicesListDescription: 'Enter the services you offer to help us find the most relevant leads for your business',
      emailPromptingTitle: 'Email Prompting',
      emailPromptingDescription: 'Set up AI-powered email sequences for your leads',
      companySettings: 'Company Settings',
      companyName: 'Company Name',
      yourCompanyName: 'Your Company Name',
      offeredService: 'Offered Service',
      offeredServicePlaceholder: 'e.g. Web Development',
      targetIndustry: 'Target Industry',
      targetIndustryPlaceholder: 'e.g. E-commerce',
      emailInterval: 'Email Interval',
      selectInterval: 'Select Interval',
      everyThreeDays: 'Every 3 days',
      weekly: 'Weekly',
      biweekly: 'Biweekly',
      monthly: 'Monthly',
      emailSequence: 'Email Sequence',
      firstEmail: 'First Email',
      firstEmailPlaceholder: 'Write an introduction email from {companyName} offering {service} services...',
      secondEmail: 'Second Email',
      secondEmailPlaceholder: 'Write a follow-up email about how our services can help businesses in the {industry} industry...',
      thirdEmail: 'Third Email',
      thirdEmailPlaceholder: 'Write a third follow-up email creating urgency...',
      fourthEmail: 'Fourth Email',
      fourthEmailPlaceholder: 'Write a final email stating this is the last reminder from {companyName}...',
      generateWithAI: 'Generate with AI',
      bookingTitle: 'Booking Email Template',
      bookingDescription: 'Configure the email template sent when a lead is ready to book a service',
      saveTemplate: 'Save Template',
      templateEditor: 'Template Editor',
      aiOptimized: 'AI-Optimized',
      useVariables: 'Use these variables in your template. They will be automatically replaced with actual data.',
      resetToDefault: 'Reset to Default',
      settingsTitle: 'Settings',
      settingsDescription: 'Configure your QuasarLeads dashboard preferences',
      saveChanges: 'Save Changes',
      companyInformation: 'Company Information',
      companyWebsite: 'Company Website',
      apiKey: 'API Key',
      apiKeyDescription: 'Required for LinkedIn and Google scraping functionality',
      aiSettings: 'AI Settings',
      aiAutoResponse: 'AI Auto-Response',
      aiAutoResponseDescription: 'Let AI automatically generate responses to lead replies',
      dashboardNotifications: 'Dashboard Notifications',
      realTimeNotifications: 'Receive real-time notifications for new leads and responses',
      emailNotifications: 'Email Notifications',
      receiveEmailNotifications: 'Get notified via email for important updates',
      advancedSettings: 'Advanced Settings',
      exportData: 'Export Data',
      exportLeadsCSV: 'Export Leads to CSV',
      downloadLeadsCSV: 'Download all your leads in CSV format',
      accountSettings: 'Account Settings',
      accountSettingsSubtitle: 'Manage your account and preferences',
      security: 'Security',
      adminPanel: 'Admin Panel',
      credentials: 'Credentials',
      profileInformation: 'Profile Information',
      profileInformationDescription: 'View and manage your account information',
      usernameLabel: 'Username',
      accountType: 'Account Type',
      verifiedLabel: 'Verified',
      unverifiedLabel: 'Unverified',
      memberSince: 'Member Since',
      changeEmail: 'Change Email',
      changeEmailDescription: 'Update your email address',
      newEmailAddress: 'New Email Address',
      currentPasswordLabel: 'Current Password',
      updateEmail: 'Update Email',
      changePassword: 'Change Password',
      changePasswordDescription: 'Update your password to keep your account secure',
      newPasswordLabel: 'New Password',
      confirmNewPasswordLabel: 'Confirm New Password',
      updatePassword: 'Update Password',
      userManagement: 'User Management',
      userManagementDescription: 'Manage user accounts and verifications',
      verify: 'Verify',
      unverify: 'Unverify',
      noUsersFound: 'No users found',
      joined: 'Joined',
      credentialsTitle: 'API & Service Credentials',
      credentialsDescriptionAdmin: 'Manage keys and connection details used by the system',
      credentialsDescriptionUser: 'Manage your personal API keys and service credentials',
      manageSubscription: 'Manage Subscription',
      updateSubscriptionPlan: 'Update your subscription plan and billing information',
      enterApiKey: 'Enter your API key',
      companyWebsitePlaceholder: 'https://yourcompany.com',
      settingsSaved: 'Settings Saved',
      settingsSavedDescription: 'Your settings have been successfully updated',
      months: 'Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec',
      sampleLeadName: 'John Smith',
      sampleCompany: 'Tech Solutions Inc.',
      sampleEmail: 'john@techsolutions.com',
      sampleDate: 'April 24, 14:00',
      calendarAndReminders: 'Calendar & Reminders',
      today: 'Today',
      day: 'Day',
      week: 'Week',
      month: 'Month',
      upcoming: 'Upcoming',
      newEvent: 'New Event',
      todaysSchedule: "Today's Schedule",
      dailySchedule: 'Daily Schedule',
      weeklySchedule: 'Weekly Schedule',
      monthlySchedule: 'Monthly Schedule',
      viewCalendar: 'View Calendar',
      noEventsScheduled: 'No Events Scheduled',
      noEventsMessage: 'You have no events scheduled for this period. Click the button below to add a new event.',
      scheduleEvent: 'Schedule Event',
      participant: 'participant',
      crmSystem: 'CRM System',
      crmSystemDescription: 'Manage your sales pipeline and track customer relationships',
      language: 'Language',
      addNewLead: 'Add New Lead',
      salesPipeline: 'Sales Pipeline',
      calendar: 'Calendar',
      integrations: 'Integrations',
      calendarIntegration: 'Calendar Integration',
      calendarIntegrationDescription: 'Connect your calendar to automatically sync meetings and appointments with your CRM',
      connectCalendar: 'Connect Calendar',
      calendlyIntegrationUpdated: 'Calendly Integration Updated',
      calendlyWebhookSaved: 'Your Calendly webhook URL has been saved',
      error: 'Error',
      enterCalendlyUrlFirst: 'Please enter your Calendly webhook URL first',
      testWebhookSent: 'Test Webhook Sent',
      testNotificationSent: 'A test notification was sent to your Calendly webhook',
      calendlyWebhookUrl: 'Calendly Webhook URL',
      calendlyWebhookPlaceholder: 'https://calendly.com/yourwebhook',
      calendlyWebhookInstructions: 'Enter the webhook URL from your Calendly account settings',
      testConnection: 'Test Connection',
      saveConnection: 'Save Connection',
      zapierIntegration: 'Zapier Integration',
      zapierAlternativeDescription: 'Alternatively, you can use Zapier to connect Calendly with QuasarLeads CRM',
      zapierWebhookUrl: 'Zapier Webhook URL',
      zapierWebhookPlaceholder: 'https://hooks.zapier.com/hooks/catch/...',
      zapierWebhookInstructions: 'Use a Zapier webhook to connect Calendly events to this CRM',
      zapierSetupGuide: 'How to set up with Zapier:',
      createNewZap: 'Create a new Zap in Zapier',
      selectCalendlyTrigger: 'Select Calendly as the trigger app',
      chooseScheduledMeeting: 'Choose "New Scheduled Meeting" as the trigger event',
      connectCalendlyAccount: 'Connect your Calendly account',
      useWebhookAction: 'Use a Webhook action to send data to QuasarLeads',
      copyWebhookUrl: 'Copy the webhook URL and paste it above',
      setupZapierIntegration: 'Setup Zapier Integration',
      leadDetails: 'Lead Details',
      details: 'Details',
      activities: 'Activities',
      status: 'Status',
      name: 'Name',
      company: 'Company',
      position: 'Position',
      email: 'Email',
      phone: 'Phone',
      leadSource: 'Lead Source',
      selectSource: 'Select source',
      notes: 'Notes',
      tags: 'Tags',
      addTag: 'Add tag',
      add: 'Add',
      addNewActivity: 'Add New Activity',
      type: 'Type',
      selectType: 'Select type',
      date: 'Date',
      describeActivity: 'Describe the activity...',
      addActivity: 'Add Activity',
      activityHistory: 'Activity History',
      noActivitiesRecorded: 'No activities recorded',
      pipelineStage: 'Pipeline Stage',
      selectStage: 'Select stage',
      dealStatus: 'Deal Status',
      won: 'Won',
      lost: 'Lost',
      lossReason: 'Loss Reason',
      selectReason: 'Select reason',
      comment: 'Comment',
      specifyReason: 'Please specify the reason...',
      cancel: 'Cancel',
      // @ts-ignore
      saveChanges: 'Save Changes',
      source_website: 'Website',
      source_linkedin: 'LinkedIn',
      source_referral: 'Referral',
      source_cold_email: 'Cold Email',
      source_event: 'Event',
      source_other: 'Other',
      stage_new_leads: 'New Leads',
      stage_called_once: 'Called Once',
      stage_called_twice: 'Called Twice',
      stage_called_three_times: 'Called Three Times',
      stage_called_four_times: 'Called Four Times',
      stage_called_five_times: 'Called Five Times',
      stage_called_six_times: 'Called Six Times',
      stage_called_seven_times: 'Called Seven Times',
      stage_qualification_call: 'Qualification Call',
      stage_meeting: 'Meeting',
      stage_follow_up: 'Follow-up',
      stage_deal: 'Deal',
      stage_follow_up_later: 'Follow-up Later',
      activity_phone_call_scheduled: 'Phone Call (Scheduled)',
      activity_qualification_call: 'Qualification Call',
      activity_demo_meeting: 'Demo / Meeting',
      activity_follow_up: 'Follow-up',
      activity_whatsapp: 'WhatsApp',
      activity_email: 'Email',
      activity_linkedin: 'LinkedIn',
      activity_incoming_call: 'Incoming Call',
      activity_outgoing_call: 'Outgoing Call',
      // Analytics & Charts
      analyseRapporten: 'Analysis & Reports',
      loading: 'Loading...',
      emailPrestaties: 'Email Performance',
      verzondenEmails: 'Sent Emails',
      ontvangenReacties: 'Received Responses',
      hoverOverGraphTooltip: '*Hover over the graph for more details',
      leadsPerSector: 'Leads by Sector',
      leadsPerPlatform: 'Leads by Platform & Engagement',
      totaalLeads: 'Total Leads',
      geopend: 'Opened',
      reacties: 'Responses',
      afspraken: 'Appointments',
      leadsPerMaand: 'Leads by Month (Last 6 Months)',
      aantalLeads: 'Number of Leads',
      mrrGroei: 'MRR Growth',
      mrrEuro: 'MRR (€)',
      downloadRapport: 'Download Report',
      // CRM Lead Details
      budget: 'Budget',
      lossDescription: 'Loss Description',
      productionBackgroundJobSystem: "🚀 Production Background Job System",
      checkHealth: "Check Health",
      testingCronjob: "Testing cronjob system...",
      cronjobTestSuccess: "✅ Cronjob test completed successfully!",
      cronjobTestFailed: "❌ Cronjob test failed",
      failedToTestCronjob: "Failed to test cronjob system",
      testCronjob: "Test Cronjob",
      localProcessing: "🛠️ Local Development Mode:",
      localProcessingDesc: "Jobs run automatically in the background for localhost testing. No Vercel Cron Jobs needed - perfect for development and testing!",
      backgroundProcessing: "Background Processing:",
      backgroundProcessingDesc: "Jobs run automatically every 5 minutes via Vercel Cron Jobs. No browser dependency - jobs continue running even when you close your browser!",
      proTimeout: "Pro Timeout:",
      proTimeoutDesc: "Each job step has 5 minutes (300 seconds) to complete.",
      // Won/Lost Stats
      wonLostAnalysis: "Won/Lost Analysis",
      wonDeals: "Won Deals",
      lostDeals: "Lost Deals",
      winRate: "Win Rate",
      totalBudget: "Total Budget",
      acrossAllDeals: "Across all deals",
      dealsByStatus: "Deals by Status",
      noDealsToDisplay: "No deals to display yet. Start by marking leads as Won or Lost in the CRM.",
      summary: "Summary",
      trends: "Trends",
      lossReasons: "Loss Reasons",
      last6Months: "Last 6 Months",
      totalBudgetLabel: "Total budget",
      lossReasonsTitle: "Loss Reasons",
      deals: "deals",
      lostBudget: "Lost budget",
      notInterested: "Not Interested",
      noBudget: "No Budget",
      noResponse: "No Response",
      choseCompetitor: "Chose Competitor",
      tooEarly: "Too Early",
      notAFit: "Not a Fit",
      other: "Other",
      unknown: "Unknown",
      totalDeals: 'Total Deals',
      sampleData: 'Sample Data',
      // Leads page translations
      enterLocations: 'Enter Locations (comma-separated)',
      locationsPlaceholder: 'Dhaka, Delhi, Hong Kong, Singapore, New York',
      locationsDescription: 'Locations Description',
      includeHighValueAnalysis: 'Include High Value Leads Analysis',
      highValueAnalysisDescription: 'Get both normal leads + enhanced high-value leads with Google Ads analysis',
      simpleCollection: 'Simple Collection: Uses only 1 SERP coin per service x location (optimized cost efficiency)',
      startSimpleCollection: 'Start Simple Collection',
      leadQuantity: 'Lead Quantity',
      selectQuantity: 'Select Quantity',
      customQuantity: 'Custom Quantity',
      enterCustomQuantity: 'Enter custom quantity',
      activeJobsInQueue: 'Active Jobs in Queue',
      activeJob: 'Active Job',
      activeJobs: 'Active Jobs',
      selectJobToView: 'Select job to view',
      viewProgress: 'View Progress',
      noActiveJobsFound: 'No active jobs found',
      jobProgress: 'Job Progress',
      close: 'Close',
      downloadCSV: 'Download CSV',
      cleanDuplicates: 'Clean Duplicates',
      cleaning: 'Cleaning...',
      cleanInvalidEmails: 'Clean Invalid Emails',
      aiAnalyzing: 'AI Analyzing...',
      addToEmailQueue: 'Add to Email Queue',
      cancelSelection: 'Cancel Selection',
      leadSelection: 'Lead Selection',
      leadsSelected: 'leads selected',
      leadSelected: 'lead selected',
      clearSelection: 'Clear Selection',
      startAutomation: 'Start Automation',
      starting: 'Starting...',
      addToCRM: 'Add to CRM',
      adding: 'Adding...',
      deleteLeads: 'Delete Leads',
      deleting: 'Deleting...',
      searchLeads: 'Search Leads',
      refreshingLeads: 'Refreshing leads...',
      loadingLeads: 'Loading leads...',
      googleAds: 'Google Ads',
      emailAutomation: 'Email Automation',
      linkedin: 'LinkedIn',
      profile: 'Profile',
      clickToCopy: 'Click to copy',
      allLeads: 'All Leads',
      completeOverview: 'Complete overview of all your leads',
      confirmDeleteLeads: 'Are you sure you want to delete {count} leads? This action cannot be undone.',
      confirmCleanupDuplicates: '⚠️ This will remove duplicate leads and merge their data. This action cannot be undone. Continue?',
      confirmCleanupEmails: '🤖 This will use AI to identify and remove leads with invalid emails (like \'your@email.com\', \'file.jpg\', etc.). This action cannot be undone. Continue?',
      aiAnalyzingEmails: '🤖 AI is analyzing emails... This may take a few minutes.',
      cleanupCompleted: '✅ Cleanup completed! Removed {duplicates} duplicates, updated {updated} leads. Final count: {final}',
      aiEmailCleanupComplete: '🤖 AI Email Cleanup Complete!\n• Checked: {checked} leads\n• Obviously Invalid: {obvious}\n• AI Detected Invalid: {ai}\n• Total Removed: {total}\n• Final Count: {final}',
      failedToCleanupDuplicates: 'Failed to cleanup duplicates',
      failedToCleanupEmails: 'Failed to cleanup invalid emails',
      downloadedLeadsToCSV: 'Downloaded {count} leads to CSV file',
      failedToDownloadCSV: 'Failed to download CSV file',
      successfullyDeletedLeads: '✅ Successfully deleted {count} leads!',
      failedToDeleteLeads: '❌ Failed to delete leads: {message}',
      failedToDeleteLeadsGeneric: 'Failed to delete leads',
      noLeadsSelected: 'No leads selected',
      totalJobs: 'total jobs',
      debug: 'Debug',
      refreshLeads: 'Refresh leads',
      downloadLeadsAsCSV: 'Download leads as CSV',
      removeDuplicateLeads: 'Remove duplicate leads',
      removeLeadsWithInvalidEmails: 'Remove leads with invalid emails using AI',
      toggleLeadSelectionMode: 'Toggle lead selection mode',
      addSelectedLeadsToEmailQueue: 'Add selected leads to email queue',
      viewAllLeads: 'View all leads',
      leadSelectionMode: 'Lead Selection: {count} lead{plural} selected',
      startAutomatedEmailSequence: 'Start automated 7-stage email sequence using your email templates and timing settings',
      addToCRMSystem: 'Add to CRM system for manual tracking and management',
      permanentlyDeleteSelectedLeads: 'Permanently delete selected leads',
      removeDuplicateLeadsAndMerge: '🗑️ Remove duplicate leads and merge their data',
      useAIToRemoveInvalidEmails: '🤖 Use AI to identify and remove leads with invalid emails',
      addToEmailQueueSelected: 'Add to Email Queue - {count} selected',
      addToCRMSelected: 'Add to CRM ({count})',
      deleteLeadsSelected: 'Delete Leads ({count})',
      cleanDuplicatesButton: 'Clean Duplicates',
      cleanInvalidEmailsButton: 'Clean Invalid Emails',
      addToEmailQueueButton: 'Add to Email Queue',
      viewAllButton: 'View All',
      closeButton: 'Close',
      refreshLeadsButton: 'Refresh leads',
      downloadCSVButton: 'Download CSV'
    },
    nl: {
      welcome: 'Welkom',
      settings: 'Instellingen',
      leads: 'Leads',
      booking: 'Boeking',
      emailPrompting: 'E-mail Prompten',
      emailResponses: 'E-mail Reacties',
      welcomeTitle: 'Welkom bij QuasarLeads',
      welcomeDescription: 'Uw AI-aangedreven dashboard voor leadgeneratie en e-mailautomatisering',
      startCollectingLeads: 'Start met Leads Verzamelen',
      overview: 'Overzicht',
      kpiDashboard: 'KPI Dashboard',
      totalLeads: 'Totaal Leads',
      readyForCollection: 'Klaar voor verzameling',
      emailsSent: 'E-mails Verzonden',
      acrossAllCampaigns: 'Over alle campagnes',
      responseRate: 'Responspercentage',
      fromSentEmails: 'Van verzonden e-mails',
      appointments: 'Afspraken',
      confirmedMeetings: 'Bevestigde meetings',
      quickActions: 'Snelle Acties',
      gettingStarted: 'Aan de Slag Gids',
      configureLeadCollection: 'Configureer Lead Verzameling',
      configureLeadCollectionDesc: 'Stel uw doeldiensten en locaties in om relevante leads te verzamelen.',
      setupEmailSequences: 'Stel E-mailreeksen in',
      setupEmailSequencesDesc: 'Maak aangepaste e-mailsjablonen en automatiseer opvolgsequenties.',
      createAppointmentTemplates: 'Maak Afspraaksjablonen',
      createAppointmentTemplatesDesc: 'Stel boekingssjablonen en bevestigingsmails in voor afspraken.',
      analyzeResults: 'Analyseer Resultaten',
      analyzeResultsDesc: 'Volg uw prestatiemetrieken en optimaliseer uw campagnes.',
      collectNewLeads: 'Nieuwe Leads Verzamelen',
      configureEmailSequences: 'E-mailreeksen Configureren',
      setupAppointmentTemplates: 'Afspraaksjablonen Instellen',
      viewCRMSystem: 'CRM Systeem Bekijken',
      recentActivities: 'Recente Activiteiten',
      noRecentActivities: 'Geen recente activiteiten',
      recentLeads: 'Recente Leads',
      viewAll: 'Alles Bekijken',
      noLeadsFound: 'Geen leads gevonden',
      lead: 'Lead',
      source: 'Bron',
      openRate: 'Openingspercentage',
      comparedToPreviousPeriod: 'Vergeleken met vorige periode',
      replyRate: 'Antwoordpercentage',
      callsScheduled: 'Geplande Gesprekken',
      thisMonth: 'Deze maand',
      conversionToCustomer: 'Conversie naar Klant',
      target: 'Doel',
      fromScheduledCalls: 'Van geplande gesprekken',
      googleAdsSuccessRate: 'Google Ads Succespercentage',
      highValueLeadsDetected: 'Hoogwaardige leads gedetecteerd',
      leadsPerMonth: 'Leads per Maand',
      emailCampaignPipelineStatus: 'E-mailcampagne Pijplijnstatus',
      scheduledAppointments: 'Geplande Afspraken',
      appointment: 'Afspraak',
      actions: 'Acties',
      note: 'Notitie',
      noAppointmentsScheduled: 'Nog geen afspraken gepland',
      refresh: 'Vernieuwen',
      activeCampaign: 'Actieve campagne',
      scheduled: 'Gepland',
      closedWon: 'Deal gesloten',
      newLeads: 'Nieuwe leads',
      closed: 'Gesloten',
      leadsCollection: 'Leads Verzameling',
      leadsCollectionTitle: "Leads Verzameling",
      leadsCollectionDescription: "Verzamel en beheer uw leads efficiënt.",
      leadsDescription: 'Configureer en start met het verzamelen van leads van LinkedIn en Google',
      enterServices: 'Voer Diensten in (komma-gescheiden)',
      servicesPlaceholder: 'Webdesign, Ontwikkeling, SEO, Marketing',
      servicesList: 'Lijst van diensten die u aanbiedt om relevante leads te vinden',
      servicesListDescription: 'Voer de diensten in die u aanbiedt om de meest relevante leads voor uw bedrijf te vinden',
      emailPromptingTitle: 'E-mail Prompten',
      emailPromptingDescription: 'Stel AI-aangedreven e-mailreeksen samen voor uw leads',
      companySettings: 'Bedrijfsinstellingen',
      companyName: 'Bedrijfsnaam',
      yourCompanyName: 'Uw Bedrijfsnaam',
      offeredService: 'Aangeboden dienst',
      targetIndustry: 'Doelbranche',
      emailInterval: 'E-mail interval',
      selectInterval: 'Selecteer interval',
      everyThreeDays: 'Elke 3 dagen',
      weekly: 'Wekelijks',
      biweekly: 'Tweewekelijks',
      monthly: 'Maandelijks',
      emailSequence: 'E-mailreeks',
      firstEmail: 'Eerste e-mail',
      secondEmail: 'Tweede e-mail',
      thirdEmail: 'Derde e-mail',
      fourthEmail: 'Vierde e-mail',
      generateWithAI: 'Genereren met AI',
      bookingTitle: 'Afspraak E-mailsjabloon',
      bookingDescription: 'Configureer het e-mailsjabloon dat wordt verzonden wanneer een lead klaar is om een dienst te boeken',
      saveTemplate: 'Sjabloon Opslaan',
      templateEditor: 'Sjabloon Editor',
      aiOptimized: 'AI-Geoptimaliseerd',
      useVariables: 'Gebruik deze variabelen in uw sjabloon. Ze worden automatisch vervangen door de werkelijke gegevens.',
      resetToDefault: 'Herstel naar Standaard',
      settingsTitle: 'Instellingen',
      settingsDescription: 'Configureer uw QuasarLeads dashboard voorkeuren',
      saveChanges: 'Wijzigingen Opslaan',
      companyInformation: 'Bedrijfsinformatie',
      companyWebsite: 'Bedrijfswebsite',
      apiKey: 'API Sleutel',
      apiKeyDescription: 'Vereist voor LinkedIn en Google scraping functionaliteit',
      aiSettings: 'AI Instellingen',
      aiAutoResponse: 'AI Auto-Antwoord',
      aiAutoResponseDescription: 'Laat AI automatisch antwoorden genereren op lead reacties',
      dashboardNotifications: 'Dashboard Meldingen',
      realTimeNotifications: 'Ontvang real-time meldingen voor nieuwe leads en reacties',
      emailNotifications: 'E-mail Meldingen',
      receiveEmailNotifications: 'Ontvang e-mailmeldingen voor belangrijke updates',
      advancedSettings: 'Geavanceerde Instellingen',
      exportData: 'Gegevens Exporteren',
      exportLeadsCSV: 'Exporteer Leads naar CSV',
      downloadLeadsCSV: 'Download al uw leads in CSV-formaat',
      accountSettings: 'Account Instellingen',
      accountSettingsSubtitle: 'Beheer uw account en voorkeuren',
      security: 'Beveiliging',
      adminPanel: 'Admin Paneel',
      credentials: 'Credentials',
      profileInformation: 'Profielinformatie',
      profileInformationDescription: 'Bekijk en beheer uw accountinformatie',
      usernameLabel: 'Gebruikersnaam',
      accountType: 'Accounttype',
      verifiedLabel: 'Geverifieerd',
      unverifiedLabel: 'Niet geverifieerd',
      memberSince: 'Lid sinds',
      changeEmail: 'E-mail Wijzigen',
      changeEmailDescription: 'Werk uw e-mailadres bij',
      newEmailAddress: 'Nieuw e-mailadres',
      currentPasswordLabel: 'Huidig wachtwoord',
      updateEmail: 'E-mail Bijwerken',
      changePassword: 'Wachtwoord Wijzigen',
      changePasswordDescription: 'Werk uw wachtwoord bij om uw account te beveiligen',
      newPasswordLabel: 'Nieuw wachtwoord',
      confirmNewPasswordLabel: 'Bevestig nieuw wachtwoord',
      updatePassword: 'Wachtwoord Bijwerken',
      userManagement: 'Gebruikersbeheer',
      userManagementDescription: 'Beheer gebruikersaccounts en verificaties',
      verify: 'Verifiëren',
      unverify: 'Verificatie intrekken',
      noUsersFound: 'Geen gebruikers gevonden',
      joined: 'Lid sinds',
      credentialsTitle: 'API & Service Credentials',
      credentialsDescriptionAdmin: 'Beheer sleutels en verbindingsdetails die door het systeem worden gebruikt',
      credentialsDescriptionUser: 'Beheer uw persoonlijke API-sleutels en service-credentials',
      manageSubscription: 'Abonnement Beheren',
      updateSubscriptionPlan: 'Werk uw abonnementsplan en factureringsgegevens bij',
      enterApiKey: 'Voer uw API-sleutel in',
      companyWebsitePlaceholder: 'https://uwbedrijf.nl',
      settingsSaved: 'Instellingen Opgeslagen',
      settingsSavedDescription: 'Uw instellingen zijn succesvol bijgewerkt',
      months: 'Jan,Feb,Mrt,Apr,Mei,Jun,Jul,Aug,Sep,Okt,Nov,Dec',
      sampleLeadName: 'Sophie de Vries',
      sampleCompany: 'TechBoost B.V.',
      sampleEmail: 's.devries@techboost.nl',
      sampleDate: '24 april, 14:00',
      calendarAndReminders: 'Kalender & Herinneringen',
      today: 'Vandaag',
      day: 'Dag',
      week: 'Week',
      month: 'Maand',
      upcoming: 'Aankomend',
      newEvent: 'Nieuwe Afspraak',
      todaysSchedule: 'Schema van Vandaag',
      dailySchedule: 'Dagelijks Schema',
      weeklySchedule: 'Wekelijks Schema',
      monthlySchedule: 'Maandelijks Schema',
      viewCalendar: 'Kalender Bekijken',
      noEventsScheduled: 'Geen Afspraken Gepland',
      noEventsMessage: 'U heeft geen afspraken gepland voor deze periode. Klik op de knop hieronder om een nieuwe afspraak toe te voegen.',
      scheduleEvent: 'Afspraak Inplannen',
      participant: 'deelnemer',
      crmSystem: 'CRM Systeem',
      crmSystemDescription: 'Beheer uw verkooppijplijn en volg klantrelaties',
      language: 'Taal',
      addNewLead: 'Nieuwe Lead Toevoegen',
      salesPipeline: 'Verkooppijplijn',
      calendar: 'Kalender',
      integrations: 'Integraties',
      calendarIntegration: 'Kalenderintegratie',
      calendarIntegrationDescription: 'Koppel uw kalender om automatisch afspraken te synchroniseren met uw CRM',
      connectCalendar: 'Kalender Koppelen',
      calendlyIntegrationUpdated: 'Calendly Integratie Bijgewerkt',
      calendlyWebhookSaved: 'Uw Calendly webhook URL is opgeslagen',
      error: 'Fout',
      enterCalendlyUrlFirst: 'Voer eerst uw Calendly webhook URL in',
      testWebhookSent: 'Test Webhook Verzonden',
      testNotificationSent: 'Een testmelding is verzonden naar uw Calendly webhook',
      calendlyWebhookUrl: 'Calendly Webhook URL',
      calendlyWebhookPlaceholder: 'https://calendly.com/uwwebhook',
      calendlyWebhookInstructions: 'Voer de webhook URL in van uw Calendly account instellingen',
      testConnection: 'Test Verbinding',
      saveConnection: 'Verbinding Opslaan',
      zapierIntegration: 'Zapier Integratie',
      zapierAlternativeDescription: 'U kunt ook Zapier gebruiken om Calendly te koppelen met QuasarLeads CRM',
      zapierWebhookUrl: 'Zapier Webhook URL',
      zapierWebhookPlaceholder: 'https://hooks.zapier.com/hooks/catch/...',
      zapierWebhookInstructions: 'Gebruik een Zapier webhook om Calendly gebeurtenissen te koppelen aan deze CRM',
      zapierSetupGuide: 'Hoe u Zapier instelt:',
      createNewZap: 'Maak een nieuwe Zap in Zapier',
      selectCalendlyTrigger: 'Selecteer Calendly als trigger app',
      chooseScheduledMeeting: 'Kies "Nieuwe Geplande Afspraak" als trigger gebeurtenis',
      connectCalendlyAccount: 'Koppel uw Calendly account',
      useWebhookAction: 'Gebruik een Webhook actie om gegevens naar QuasarLeads te sturen',
      copyWebhookUrl: 'Kopieer de webhook URL en plak deze hierboven',
      setupZapierIntegration: 'Zapier Integratie Instellen',
      leadDetails: 'Lead Details',
      details: 'Details',
      activities: 'Activiteiten',
      status: 'Status',
      name: 'Naam',
      company: 'Bedrijf',
      position: 'Functie',
      email: 'E-mail',
      phone: 'Telefoon',
      leadSource: 'Lead Bron',
      selectSource: 'Selecteer bron',
      notes: 'Notities',
      tags: 'Tags',
      addTag: 'Tag toevoegen',
      add: 'Toevoegen',
      addNewActivity: 'Nieuwe Activiteit Toevoegen',
      type: 'Type',
      selectType: 'Selecteer type',
      date: 'Datum',
      describeActivity: 'Beschrijf de activiteit...',
      addActivity: 'Activiteit Toevoegen',
      activityHistory: 'Activiteitengeschiedenis',
      noActivitiesRecorded: 'Geen activiteiten geregistreerd',
      pipelineStage: 'Pijplijn Fase',
      selectStage: 'Selecteer fase',
      dealStatus: 'Deal Status',
      won: 'Gewonnen',
      lost: 'Verloren',
      lossReason: 'Verlies Reden',
      selectReason: 'Selecteer reden',
      comment: 'Opmerking',
      specifyReason: 'Geef de reden op...',
      cancel: 'Annuleren',
      // @ts-ignore
      saveChanges: 'Wijzigingen Opslaan',
      source_website: 'Website',
      source_linkedin: 'LinkedIn',
      source_referral: 'Doorverwijzing',
      source_cold_email: 'Koude E-mail',
      source_event: 'Evenement',
      source_other: 'Anders',
      stage_new_leads: 'Nieuwe Leads',
      stage_called_once: 'Eén Keer Gebeld',
      stage_called_twice: 'Twee Keer Gebeld',
      stage_called_three_times: 'Drie Keer Gebeld',
      stage_called_four_times: 'Vier Keer Gebeld',
      stage_called_five_times: 'Vijf Keer Gebeld',
      stage_called_six_times: 'Zes Keer Gebeld',
      stage_called_seven_times: 'Zeven Keer Gebeld',
      stage_qualification_call: 'Kwalificatiegesprek',
      stage_meeting: 'Meeting',
      stage_follow_up: 'Opvolging',
      stage_deal: 'Deal',
      stage_follow_up_later: 'Later Opvolgen',
      activity_phone_call_scheduled: 'Telefoongesprek (Gepland)',
      activity_qualification_call: 'Kwalificatiegesprek',
      activity_demo_meeting: 'Demo / Meeting',
      activity_follow_up: 'Opvolging',
      activity_whatsapp: 'WhatsApp',
      activity_email: 'E-mail',
      activity_linkedin: 'LinkedIn',
      activity_incoming_call: 'Inkomend Gesprek',
      activity_outgoing_call: 'Uitgaand Gesprek',
      // Analytics & Charts
      analyseRapporten: 'Analyse & Rapporten',
      loading: 'Laden...',
      emailPrestaties: 'E-mail Prestaties',
      verzondenEmails: 'Verzonden E-mails',
      ontvangenReacties: 'Ontvangen Reacties',
      hoverOverGraphTooltip: '*Hover over de grafiek voor meer details',
      leadsPerSector: 'Leads per Sector',
      leadsPerPlatform: 'Leads per Platform & Engagement',
      totaalLeads: 'Totaal Leads',
      geopend: 'Geopend',
      reacties: 'Reacties',
      afspraken: 'Afspraken',
      leadsPerMaand: 'Leads per Maand (Laatste 6 Maanden)',
      aantalLeads: 'Aantal Leads',
      mrrGroei: 'MRR Groei',
                   mrrEuro: 'MRR (€)',
      downloadRapport: 'Download Rapport',
      // CRM Lead Details
      budget: 'Budget',
      lossDescription: 'Verlies Beschrijving',
      productionBackgroundJobSystem: "🚀 Productie Achtergrondtaak Systeem",
      checkHealth: "Controleer Gezondheid",
      testingCronjob: "Cronjob-systeem testen...",
      cronjobTestSuccess: "✅ Cronjob-test succesvol voltooid!",
      cronjobTestFailed: "❌ Cronjob-test mislukt",
      failedToTestCronjob: "Kan cronjob-systeem niet testen",
      testCronjob: "Test Cronjob",
      localProcessing: "🛠️ Lokale Ontwikkelmodus:",
      localProcessingDesc: "Taken worden automatisch op de achtergrond uitgevoerd voor localhost testen. Geen Vercel Cron Jobs nodig - perfect voor ontwikkeling en testen!",
      backgroundProcessing: "Achtergrondverwerking:",
      backgroundProcessingDesc: "Taken worden automatisch elke 5 minuten uitgevoerd via Vercel Cron Jobs. Geen browserafhankelijkheid - taken blijven doorgaan, zelfs als u uw browser sluit!",
      proTimeout: "Pro Tijdslimiet:",
      proTimeoutDesc: "Elke taakstap heeft 5 minuten (300 seconden) om te voltooien.",
      // Won/Lost Stats
      wonLostAnalysis: "Gewonnen/Verloren Analyse",
      wonDeals: "Gewonnen Deals",
      lostDeals: "Verloren Deals",
      winRate: "Winstpercentage",
      totalBudget: "Totaal Budget",
      acrossAllDeals: "Over alle deals",
      dealsByStatus: "Deals per Status",
      noDealsToDisplay: "Nog geen deals om weer te geven. Begin met het markeren van leads als Gewonnen of Verloren in de CRM.",
      summary: "Samenvatting",
      trends: "Trends",
      lossReasons: "Verlies Redenen",
      last6Months: "Laatste 6 Maanden",
      totalBudgetLabel: "Totaal budget",
      lossReasonsTitle: "Verlies Redenen",
      deals: "deals",
      lostBudget: "Verloren budget",
      notInterested: "Niet Geïnteresseerd",
      noBudget: "Geen Budget",
      noResponse: "Geen Reactie",
      choseCompetitor: "Koos Concurrent",
      tooEarly: "Te Vroeg",
      notAFit: "Geen Match",
      other: "Anders",
      unknown: "Onbekend",
      totalDeals: 'Totaal Deals',
      sampleData: 'Voorbeeld Gegevens',
      // Leads page translations
      enterLocations: 'Voer Locaties in (komma-gescheiden)',
      locationsPlaceholder: 'Amsterdam, Rotterdam, Den Haag, Utrecht, Eindhoven',
      locationsDescription: 'Locaties Beschrijving',
      includeHighValueAnalysis: 'Hoogwaardige Leads Analyse Inclusief',
      highValueAnalysisDescription: 'Krijg zowel normale leads + verbeterde hoogwaardige leads met Google Ads analyse',
      simpleCollection: 'Eenvoudige Verzameling: Gebruikt slechts 1 SERP munt per dienst x locatie (geoptimaliseerde kostenefficiëntie)',
      startSimpleCollection: 'Start Eenvoudige Verzameling',
      leadQuantity: 'Lead Aantal',
      selectQuantity: 'Selecteer Aantal',
      customQuantity: 'Aangepast Aantal',
      enterCustomQuantity: 'Voer aangepast aantal in',
      activeJobsInQueue: 'Actieve Taken in Wachtrij',
      activeJob: 'Actieve Taak',
      activeJobs: 'Actieve Taken',
      selectJobToView: 'Selecteer taak om te bekijken',
      viewProgress: 'Bekijk Voortgang',
      noActiveJobsFound: 'Geen actieve taken gevonden',
      jobProgress: 'Taak Voortgang',
      close: 'Sluiten',
      downloadCSV: 'Download CSV',
      cleanDuplicates: 'Duplicaten Opschonen',
      cleaning: 'Opschonen...',
      cleanInvalidEmails: 'Ongeldige E-mails Opschonen',
      aiAnalyzing: 'AI Analyseert...',
      addToEmailQueue: 'Toevoegen aan E-mail Wachtrij',
      cancelSelection: 'Selectie Annuleren',
      leadSelection: 'Lead Selectie',
      leadsSelected: 'leads geselecteerd',
      leadSelected: 'lead geselecteerd',
      clearSelection: 'Selectie Wissen',
      startAutomation: 'Automatisering Starten',
      starting: 'Starten...',
      addToCRM: 'Toevoegen aan CRM',
      adding: 'Toevoegen...',
      deleteLeads: 'Leads Verwijderen',
      deleting: 'Verwijderen...',
      searchLeads: 'Leads Zoeken',
      refreshingLeads: 'Leads vernieuwen...',
      loadingLeads: 'Leads laden...',
      googleAds: 'Google Ads',
      emailAutomation: 'E-mail Automatisering',
      linkedin: 'LinkedIn',
      profile: 'Profiel',
      clickToCopy: 'Klik om te kopiëren',
      allLeads: 'Alle Leads',
      completeOverview: 'Volledig overzicht van al uw leads',
      confirmDeleteLeads: 'Weet u zeker dat u {count} leads wilt verwijderen? Deze actie kan niet ongedaan worden gemaakt.',
      confirmCleanupDuplicates: '⚠️ Dit zal dubbele leads verwijderen en hun gegevens samenvoegen. Deze actie kan niet ongedaan worden gemaakt. Doorgaan?',
      confirmCleanupEmails: '🤖 Dit zal AI gebruiken om leads met ongeldige e-mails te identificeren en te verwijderen (zoals \'uw@email.nl\', \'bestand.jpg\', etc.). Deze actie kan niet ongedaan worden gemaakt. Doorgaan?',
      aiAnalyzingEmails: '🤖 AI analyseert e-mails... Dit kan enkele minuten duren.',
      cleanupCompleted: '✅ Opschoning voltooid! {duplicates} duplicaten verwijderd, {updated} leads bijgewerkt. Eindtotaal: {final}',
      aiEmailCleanupComplete: '🤖 AI E-mail Opschoning Voltooid!\n• Gecontroleerd: {checked} leads\n• Duidelijk Ongeldig: {obvious}\n• AI Gedetecteerd Ongeldig: {ai}\n• Totaal Verwijderd: {total}\n• Eindtotaal: {final}',
      failedToCleanupDuplicates: 'Kan duplicaten niet opschonen',
      failedToCleanupEmails: 'Kan ongeldige e-mails niet opschonen',
      downloadedLeadsToCSV: '{count} leads gedownload naar CSV bestand',
      failedToDownloadCSV: 'Kan CSV bestand niet downloaden',
      successfullyDeletedLeads: '✅ {count} leads succesvol verwijderd!',
      failedToDeleteLeads: '❌ Kan leads niet verwijderen: {message}',
      failedToDeleteLeadsGeneric: 'Kan leads niet verwijderen',
      noLeadsSelected: 'Geen leads geselecteerd',
      totalJobs: 'totaal taken',
      debug: 'Debug',
      refreshLeads: 'Leads vernieuwen',
      downloadLeadsAsCSV: 'Download leads als CSV',
      removeDuplicateLeads: 'Dubbele leads verwijderen',
      removeLeadsWithInvalidEmails: 'Leads met ongeldige e-mails verwijderen met AI',
      toggleLeadSelectionMode: 'Lead selectiemodus wisselen',
      addSelectedLeadsToEmailQueue: 'Geselecteerde leads toevoegen aan e-mail wachtrij',
      viewAllLeads: 'Alle leads bekijken',
      leadSelectionMode: 'Lead Selectie: {count} lead{plural} geselecteerd',
      startAutomatedEmailSequence: 'Start geautomatiseerde 7-fase e-mailreeks met uw e-mailsjablonen en timing instellingen',
      addToCRMSystem: 'Toevoegen aan CRM systeem voor handmatige tracking en beheer',
      permanentlyDeleteSelectedLeads: 'Geselecteerde leads permanent verwijderen',
      removeDuplicateLeadsAndMerge: '🗑️ Dubbele leads verwijderen en hun gegevens samenvoegen',
      useAIToRemoveInvalidEmails: '🤖 AI gebruiken om leads met ongeldige e-mails te identificeren en te verwijderen',
      addToEmailQueueSelected: 'Toevoegen aan E-mail Wachtrij - {count} geselecteerd',
      addToCRMSelected: 'Toevoegen aan CRM ({count})',
      deleteLeadsSelected: 'Leads Verwijderen ({count})',
      cleanDuplicatesButton: 'Duplicaten Opschonen',
      cleanInvalidEmailsButton: 'Ongeldige E-mails Opschonen',
      addToEmailQueueButton: 'Toevoegen aan E-mail Wachtrij',
      viewAllButton: 'Alles Bekijken',
      closeButton: 'Sluiten',
      refreshLeadsButton: 'Leads vernieuwen',
      downloadCSVButton: 'Download CSV'
    }
  }
};

const languageSlice = createSlice({
  name: 'language',
  initialState,
  reducers: {
    setLanguage: (state, action: PayloadAction<LanguageCode>) => {
      state.currentLanguage = action.payload;
    },
  },
});

export const { setLanguage } = languageSlice.actions;
export default languageSlice.reducer;